/*---------------------------------------------------------------------------*\
  ###### ###### |
  ##       ##   |  Essential Training: The Open Source Management Tool
  ######   ##   |  Copyright (C) 2025
  ##       ##   |
  ######   ##   |
-------------------------------------------------------------------------------
License

Class
    et::helloWorld
Description
    Class helloWorld that prints helloWorld to the screen.
SourceFiles
    helloWorld.C
\*---------------------------------------------------------------------------*/

#ifndef SRC_VARIABLES_HELLOWORLD_H_
#define SRC_VARIABLES_HELLOWORLD_H_





#endif /* SRC_VARIABLES_HELLOWORLD_H_ */
